from main import *

def test_caesar():
  assert caesar("FRIENDSROMANSCOUNTRYMENLENDMEYOUREAR", -20) == "LXOKTJYXUSGTYIUATZXESKTRKTJSKEUAXKGX"
  assert caesar("ABCDEFGHIJKLMNOPQRSTUVWXYZ", -3) == "XYZABCDEFGHIJKLMNOPQRSTUVW"
  assert cesar_encrypt("LXOKTJYXUSGTYIUATZXESKTRKTJSKEUAXKGX", 20) == "FRIENDSROMANSCOUNTRYMENLENDMEYOUREAR"
